: .string "label length zero"
AA012345678901234567890123456789: .string "label length 32"
@r1: .string "reserved register"
jmp: .string "reserved opcode"
data: .string "reserved directive"
invalid$character: .string "invalid character"
invalid_character: .string "invalid character"
0StartWithNumber: .string "doesn't start with a letter"
LABEL: .string "original"
LABEL: .string "copy"